### ISSUE TITLE
Support for creating orders within admin panel

### ISSUE THREAD

**Issue by ssx** [wexo/module-shipping#1]
We have a client using this extension and it appears to work fine on the frontend where checkoutSession is present.

However, the extension falls over when used in the admin panel to create an order as wexo_shipping_data is never set on the quote. 

The plugin `Wexo/Shipping/Plugins/Checkout/ShippingInformationManagementPlugin.php` won't execute when an order is created via the panel. Is this a use case you can cover?

**Comment by ssx** [comment]
@wexomartin @wexo-team @wexotht @WexoRene @WebKenth

**Comment by wexotht** [comment]
@ssx the module does not support admin orders, so you would need to extend it yourself.

**Comment by ssx** [comment]
@wexotht oooft. Thanks for the speedy response after being prompted!
